version: '1.0'
services:
    postgres:
        image: postgres
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres_test
          - POSTGRES_HOST=postgres
          - POSTGRES_PORT=5432
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        expose:
          - 5432
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ../sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
          # copy the sql script to fill tables
          - ./mock_data.sql:/docker-entrypoint-initdb.d/mock_data.sql
    node:
      image: "node:12-alpine3.14"
      user: "node"
      working_dir: ../../server
      environment:
      - NODE_ENV=production
      volumes:
      - ./:/../../server
      expose:
      - 3001
      command: "npm run startdev"


#https://levelup.gitconnected.com/creating-and-filling-a-postgres-db-with-docker-compose-e1607f6f882f
